### ISSUE TITLE
Undefined control sequence

### ISSUE THREAD

**Issue by raphenya** [paezha/macdown#2]
@paezha I installed the macdown framework for the macthesis but I'm getting the following error:

```
! Undefined control sequence.
<write> \space \acknowledgementname 
```
I'm new to using Rmarkdown, please help.

Cheers,
Amos.

**Comment by paezha** [comment]
@raphenya could you please post a reproducible example? When and how does the issue arise?

**Comment by paezha** [comment]
@raphenya

I found the issues with the support latex files that caused errors leading to "! Undefined control sequence". Please install the latest version (0.1.1) where this is hopefully fixed. Let me know if you still cannot knit.

**Comment by raphenya** [comment]
@paezha Thank you. I don't see that now after downloading version 0.1.1.
