### ISSUE TITLE
Reference  not wrapping properly

### ISSUE THREAD

**Issue by raphenya** [paezha/macdown#4]
@paezha which parameter do I set to prevent reference not wrapping properly.

![nowrap](https://user-images.githubusercontent.com/972724/219720577-f4d0a4f6-b1a5-4f72-b76f-acd42b43f64e.jpg)

**Comment by paezha** [comment]
I updated the template to use package xurl and the macro \sloppy to break long urls in the list of references. It works in my system, please check.
